---
title: "Bureaucrats"
execute:
    echo: false
    output: asis
---

The Bureaucrats are a faction endemic to civilizations. They are a memeplex and a collection of methods more than they are a group of individual agents. They are not spread through spores and disease as the Legions are, but through information and the soft tissue of social connections. They share the same fundamental aim as the Legions, to self-perpetuate, consume, and multiply.  

They are a dense autonomous patchwork of contracts, debts, obligations, and records. Many of these documents have outlived their original purpse, but through addendums, conditions, and stipulations, they persist as perversions of their original forms. It isn't known who started the network or whether its creation was intentional. The network may have been an attempt to create laws that could themselves govern, interpret, and enforce.  

The Bureau's strength lies in their arcane use of information and agreements, not brute force. They rely on others to provide force. Sometimes they will formally parner with a group or civilization, sometimes they slowly permeate, infect, and ultimately capture the group.

## The Forerunner / Receptionist

### Description

A black cylinder is driven through a thick stack of written records and into the head of the slumped creature. Only the thing's gumless wheezing mouth is visible. The pages covering its face are of all sizes. They are small cards, letters, entire scrolls, they are made of ancient papyrus and fine white cardstock, they are clay tablets, leaves, scalps, hides. Covering these records are handprints, wild script, dead languages, moving glyphs, bright red blood, every form of marking. Curdled black fluid oozes lazily from around the stack and down the front of the its atrophied body. It is fat and weak. It smells like mildew. It sits hunched over a thin table. It wears a collared shirt.  

### First Encounter

It's friendly. It asks questions about superficial qualities, name, eye color, height, etc. Then it starts asking innocuous questions about both the subject’s current state and some recent events the subject has experienced. It knows things it should not know. It requires answers from the subject, it requires that information is confirmed. As the conversation progresses it asks increasingly meaningless semantic questions. The questions become more invasive. It to asks its questions while darkly hinting at terrible consequences should the wrong answer be given. It asks the subject to pick from a set of nearly identical options. It is patient. It is meticulous.  

As answers are given, it will tear out a stake from its pale flesh. The stake might be a pen or it might just be used as one. It patiently records what is said. It asks the same questions over and over in slightly different forms, explaining how the questions are different when challenged.  

It will insist that the subject is lucky to have run across the Bureau when they did, otherwise their debts and obligations may have grown to catastrophic proportions, now at least the subject can take control.  

As the stake runs out of ink the Bureaucrat will drive it back into the wound to refill it. As the interaction progresses it will insist that the subject take certain forms and pens, filling out the forms, recording and reporting their actions, submitting the forms. It will insist that, to better make sure the forms are tracked and kept safe, the subject simply *must* allow the bureaucrat to attach the form directly to the subject with a small pin. This is, of course, just a small note to be attached with a small pin, it's a convenient magic that allows the subject to never misplace the form.  

The more information a subject gives and the more a subject engages, the more power the Bureau has over the subject. The Receptionist might first appear when the character is weak or in need, offering a service, information, or healing. It never specifies what it wants in return, if asked it will give a long explanation about how the service is not only free but it also entitles you to unspecified future services, advantages, and "opportunities". If pressed it might admit that yes there could be some minor service fees but these are merely a formality, they can be waived or some arrangement could be found.  

The Receptionist is after two things, information and some reason to be involved. It wants the subject to be visible, registered, quantified. It wants a confirmation of some instance in which the subject was wronged or perhaps wronged another. It wants the subject to accept some aid from the Bureau or accept some deal with the Bureau. The Receptionist is almost always the first member of the Bureau that any given character meets. 

### Misc.

When faced with a Receptionist the best move is to say nothing and kill it where it sits. This will make an enemy of the faction unless it is done from stealth or otherwise untraceable.

The Bureau cannot see art. It is literally invisible to them, its effects unknowable. Because of this it is not uncommon for illiterate travelers to carry books of poetry in order to beat to death Bureaucrats that appear in front of them.

The body of a Bureaucrat is good as a source of cheap ink and kindling.

<!-- ## Mechanics -->



<!-- Need to add more mobs, men in paper armor, slimes but all paper, look at historical paper armor -->
<!-- This should be a [curse] heavy faction, inflecting nonsense curses like only being able to move left (you can just turn so that whatever direction you want to move is relatively left of you...) having to follow all sorts of bizarre arcane requirements before doing basic tasks, not being able to do basic tasks-->
<!-- the health insurance faction -->

