---
title: Crust Punks
execute:
    echo: false
    output: asis
---


TODO: This section really highlights the problems with the convention of referring to the alchemical resource of "SALT" in all caps and the inert version in lowercase. Additionally there are only a few types of crust punks, and they're not very important, but they still end up in this section... Maybe that's fine?

They are SALT encrusted and delusional. They know the Art of Continuous Secretion. Their skin is covered in layers of hard grey crystal salt. Their body constantly produces SALT, so they have to constantly burn SALT to stay alive. Having a lot of SALT makes them near superhuman, having little cripples them. They must always stay awake as SALT buildup would kill them in their sleep. The solution to their exhaustion and the mental toll of their sleeplessness is burning more SALT. This abuse of SALT wears them down mentally and physically, a side effect that can only be addressed with even more SALT. Their dependence on SALT tends to outpace their production, and they live in a frantic search for more.

Their fingers are sharp clumsy daggers of salt. Their limited hand mobility makes them bad at using most weapons. When they fight, salt armor covers and envelopes their body. They fight "unarmed", with enormous spiked fists made of salt. Most of them fight like terrifying incoherently screaming superhuman brawlers in grinding mineral plate armor. A few crust punks instead burn their SALT by moving very quickly, cutting with enormous katars fused to their closed fist during combat. Crust punks do not wear armor, it would just constrain their natural salt armor.  

Some crust punks are miners who rejected a life of toil, preferring a short brutal life of glorious combat. It's common for powerful or sloppy crust punks to die crystallized by their own continuous SALT production, leaving behind a sparkling statue.

### Gameplay Note

Players might be able to learn unarmed techniques (including with brass knuckles, push-daggers) and improved physical augmentation through salt from them, but more likely they're going to get jumped by a bunch of crust punks who beat them and take their SALT.  