# Harvesters

The bones of things persist long after the soul has left, substantiating essences and legacies. The skin is superficial. It has no truth. It is temporary protection against the world. The bones do not lie, they persist long after life, but they do not cling to the soul. The skin does cling, if only weakly. Harvesters know this.

The Harvester's mind howls with the whirling souls of his victims, trapped under his skin. Harvesters carry large cruel bludgeoning weapons to kill or incapacitate while preserving the skin. They carry razor sharp sickles and knives, peelers with which they flay the living or recently deceased. They eat their victim's skin, trapping the soul before it leaves the body. They worship the Flayed God who is said to have been a man who ate a thousand great souls before eating his own skin and ascending to Godhood. As they consume they grow more powerful and more mad. They are hated and feared by anything that might become their victim. Bugs, funginids, and constructs are often accused of working with them.
<!-- kmart ass godskin apostles -->