Mist does not always obscure vision, it is not always solid. Some things hide in the mist, sometimes the mist simply lies. The mist is malleable and alive.
Having it obscure vision like an object made DMing hard, it was effectively a fog of war but with a lot of extra parts and mechanics. Too much.  
Mist can create a sort of combined claustrophobia and agoraphobia. There is a great deal of space all around you but you cannot into it, you do not know what is in it.

## On Mist Breathing

Some people can breathe the mist in, swim through it, even fly through it. In general, this is controlled with an upward force on an inhale and a downward force (or for more advanced users, potentially no force) on an exhale.  

Breathing the mist has side effects, mainly that one becomes more like the things in the mist, pale and alien. Sometimes those who breathe in the mist become unable to survive outside of the mist. 

Spoiler territory.

Travelers from the mist that have grown dependent on it must use a rebreather, most often embedded in a mask. They practice a sort of circular breathing. This is pretty unpleasant, it can even feel  unsanitary. The masks typically have a valve through which clean air can be brought in and one through which mist can be exhaled.

## Setpiece: Whaling, Hunting

Hunting in the mists is dangerous and lucrative. The mists are full of terrifying, dangerous, and enormous creatures whose oil, blood, eyes, fins, bones, are exteremly valuable. 
There are many designs for traversing the mists, Rafts pulled by flying creatures, zeppelins, and rumors of much stranger ships using arcane propulsion systems. Ships traveling through the mist need closed cabins, fires on the deck to ward the mist away or fans. The sailors often have breathing filters, often mounted inside of inverse mist-masks, styled to look like the real thing.

An easy setpiece would be to have the characters work for passage on a whaling vessel, or just work on one. Whaling campaign???

Need a table for the deleterious effects of mist breathing, growing fins, going blind, only being able to breathe the mist, various delusions, overpowering desire to hunt and eat schools of fish. This sort of thing. Higher probability of worse outcomes as you breathe more in, some small possibility of good outcomes.