project:
  output-dir: docs
  type: website

format:
  html:
    number-sections: false
    toc: true
    theme:
      - litera
      - custom.scss

website:
  title: "citatel"
  repo-url: https://github.com/ikolith/citatel
  favicon: "./assets/images/favicons/favicon.ico"
  description: "The fooligan's curse."
  page-navigation: true
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - book/about.qmd # ABOUT
      - book/quickstart.qmd # QUICKSTART
      - "book/p1_rules_and_character_creation/s1_rules/rules.qmd" # RULES, previously a whole folder
      - section: "Character Creation"
        contents:
          - book/p1_rules_and_character_creation/s2_character_creation/how_to_character_creation.md
          - book/p1_rules_and_character_creation/s2_character_creation/prerolls.md
          - book/p1_rules_and_character_creation/s2_character_creation/shopping.qmd
      - section: "Content"
        contents:
          - book/p2_content/s1_content/unaffiliated_entities.md
          - book/p2_content/s1_content/unaffiliated_npcs_and_their_entities.md
          - book/p2_content/s1_content/groups_and_their_entities.md
      - section: Worldbuilding # previously "Lore and Worldbuilding", will include the Language section
        contents:
          - auto: book/p3_worldbuilding/shipped/*
      - section: Adventures # previously "Campaigns and Adventures"
      - text: "---"
      - section: "Creation Guides"
        contents:
          - auto: book/creation/*
      - section: Code and Downloads
        contents:
          - auto: book/code_and_downloads/*
      - section: Motivations and Misc. # previously "Addendeums, Motivations, and Miscellaneous"
        contents:
          - auto: book/p5_addendums_motivations_misc/shipped/*
