project:
  output-dir: docs
  type: website

number-sections: true

website:
  title: "citatel"
  favicon: "./assets/images/favicons/favicon.ico"
  description: "The fooligan's curse."
  page-navigation: true
  sidebar:
    style: "docked"
    contents:
      - section: "About"
      - section: "Quickstart"
      - "book/p1_rules_and_character_creation/s1_rules/rules.qmd" # Rules
      - section: "Character Creation"
        contents:
          - book/p1_rules_and_character_creation/s2_character_creation/how_to_character_creation.md
          - book/p1_rules_and_character_creation/s2_character_creation/prerolls.md
          - book/p1_rules_and_character_creation/s2_character_creation/shopping.qmd
      - section: "Content"
        contents:
          - book/p2_content/s1_content/unaffiliated_entities.md
          - book/p2_content/s1_content/unaffiliated_npcs_and_their_entities.md
          - book/p2_content/s1_content/groups_and_their_entities.md
      - section: Worldbuilding # previously "Lore and Worldbuilding", will include the Language section
      - section: Adventures # previously "Campaigns and Adventures"
      - text: "---"
      - section: "Creation Guides"
      - section: Motivations, and Misc. # previously "Addendeums, Motivations, and Miscellaneous"

format:
  html:
    number-sections: false
    toc: true
    theme:
      - litera
      - custom.scss
