project:
  output-dir: docs
  type: website
  render:
    - "*.qmd"
    - "!old/"

format:
  html:
    number-sections: false
    toc: true
    theme:
      light: custom-light.scss
      dark: custom-dark.scss
#  pdf: #how do I make this all go into the same pdf instead of multiple files? Is that the "book" "type" setting in "project"?? This is poorly documented...
#    number-sections: true

website:
  title: "citatel"
  repo-url: https://github.com/ikolith/citatel
  favicon: "./assets/images/favicons/favicon.ico"
  description: "The fooligan's curse."
  page-navigation: true
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "About"
        contents:
          - book/about/mutiny.qmd
          - book/about/about.qmd
      - section: "Rules"
        contents:
          - book/actlite/sixtem.qmd
          - book/actlite/tactile.qmd
          - book/actlite/social.qmd
          - book/actlite/mechanics-misc.qmd
          - book/actlite/talaje.qmd
      - section: "Stuff"
        contents:
          - book/stuff/basic.qmd
          - book/stuff/spoilers.qmd

      # - section: "Menagerie"
      #   contents:

      # - section: "Adventures"
      #   contents:

      # - section: "Resources"
      #   contents:

      # - section: "Posts"
      #   contets:
