project:
  output-dir: docs
  type: website
  render:
    - "*.qmd"
    - "!old/"

format:
  html:
    number-sections: false
    toc: true
    theme:
      light: custom-light.scss
      dark: custom-dark.scss
    #  pdf: #how do I make this all go into the same pdf instead of multiple files? Is that the "book" "type" setting in "project"?? This is poorly documented...
    #    number-sections: true
  pdf:
    latex-auto-install: true
    #documentclass: "scrbook"
    # tbl-colwidths: true # need to instead just specify spacing for specific tables
    fontfamily: libertinus
    geometry:
      - nomarginpar
      - top=0.5in
      - bottom=0.5in
      - outer=0.5in
      - inner=0.5in
    number-sections: false
    toc: false

website:
  title: "citatel"
  repo-url: https://github.com/ikolith/citatel
  favicon: "./assets/images/favicons/favicon.ico"
  page-navigation: true

  sidebar:
    openSidebar: true
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "About"
        contents:
          - book/about/mutiny.qmd
          #- book/about/about.qmd
      - book/rules.qmd
      - section: "Skills, Weapons, Items"
        contents:
          - book/stuff/basic.qmd
          - book/stuff/spoilers.qmd
      # - section: "Menagerie"
      #   contents: "book/menagerie/*.qmd"
