project:
  output-dir: docs
  type: website

format:
  html:
    number-sections: false
    toc: true
    theme:
      light: custom-light.scss
      dark: custom-dark.scss
#  pdf: #how do I make this all go into the same pdf instead of multiple files? Is that the "book" "type" setting in "project"?? This is poorly documented...
#    number-sections: true

website:
  title: "citatel"
  repo-url: https://github.com/ikolith/citatel
  favicon: "./assets/images/favicons/favicon.ico"
  description: "The fooligan's curse."
  page-navigation: true
  sidebar:
    style: "docked"
    collapse-level: 1
    # contents:
      # - book/about.qmd # ABOUT
      # - section: "Rules"
      #   contents:
      #     - auto: "actlite/rules_and_character_creation/rules.qmd"

      # - book/quickstart.qmd # QUICKSTART
      # - section: "Rules"
      #   contents:
      #     - auto: "book/p1_rules_and_character_creation/s1_rules/*"
      # - section: "Character Creation"
      #   contents:
      #     - book/p1_rules_and_character_creation/s2_character_creation/how_to_character_creation.md
      #     - book/p1_rules_and_character_creation/s2_character_creation/prerolls.md
      #     - book/p1_rules_and_character_creation/s2_character_creation/shopping.qmd
      # - section: "Content"
      #   contents:
      #     - auto: book/p2_content/*
      # - section: Worldbuilding # previously "Lore and Worldbuilding", will include the Language section
      #   contents:
      #     - auto: book/p3_worldbuilding/shipped/*
      # - section: Adventures # previously "Campaigns and Adventures"
      # - text: "---"
      # - section: "Creation Guides"
      #   contents:
      #     - auto: book/creation/*
      # - section: Code and Downloads
      #   contents:
      #     - auto: book/code_and_downloads/*
      #     - book/utils/chadwriter/chadwriter.qmd
      # - section: Motivations and Misc. # previously "Addendeums, Motivations, and Miscellaneous"
      #   contents:
      #     - auto: book/p5_addendums_motivations_misc/shipped/*
