#!/bin/sh
echo "Git pre-commit hook running now."
#mypy update.py cli.py; 
if pytest ttrpyg/ttrpyg/tests.py; then
    echo "Python's Black:"
    black .
    # Add any other commands you want to run if tests pass here
else
    echo "Tests failed. Commit aborted."
    exit 1
fi
