# Core Rules

## Characters 

A basic player character statblock looks like this:

Health: (3)9  
Movement Speed: 4  

STR: 0  
AGI: 0  
WIL: 0  
PER: 0  
SOC: 0  

### Health

Character health is tracked as (X)Y where X is critical or “crit” health and Y is standard health. When crit health reaches 0, the character falls unconscious and begins dying. When a character runs out of standard health all subsequent damage reduces crit health. Crit damage reduces crit health directly, it does not matter how much standard health a character still has. Crit damage is notated with parentheses.

This health score of (3)9 is higher than what most people have! a very old or frail person might be (1)1, a normal adult might be (2)6. The default character block with (3)9 health and 0s for all attributes represents a healthy, able person with no deficiencies.

### Movement Speed 

"Movement Speed" determines how many spaces a character moves when they spend 1 AP to move during initaitive.

### Attributes

Attribute scores are not mandatory descriptions of qualities. They represent abilities or tools that the character has. They tend to range from -3 to +3. The attribute score is the same as the modifier on a check using that attribute. The “passive” score, the score that other characters roll against, is 6+SCORE. If you do not have an attribute score, it is not a narrative tool that you use to solve problems. You can have attribute scores not listed here.

This set of scores is listed because they are the “defensive” attributes. That means these are the only attributes that other characters are allowed to roll checks against. If you do not have an attribute score, any checks made against that attribute succeed automatically. 

#### STR / Strength

Strength is used to perform actions like lifting or breaking things as well as some actions like grappling. It’s also used to resist physical conditions like poison, disease, and exhaustion.

#### AGI / Agility

AGI is your ability to evade attacks, grab on to ledges to keep yourself from falling, avoid falling rocks, etc. It is your ability to avoid physical danger.

It is also your ability to do a flip, jump over a chasm, etc. This is not your DEX / Dexterity! DEX is your fine motor skills, your ability to do card tricks, pickpocket, and juggle. DEX is not a “defensive” score.

##### Attack Checks

Attacks are checks against passive AGI. The attacker wins ties. Some mechanics like armor can replace passive AGI in the context of attack checks.

#### WIL / Will

WIL is your ability to resist mental conditions like fear. It is used to resist many supernatural effects. It is also used for most supernatural abilities, like writing hexes.

#### PER / Perception

PER is your resistance to stealth and being tricked.

It is also your ability to investigate, spot things other people miss, quickly find things, etc.

#### SOC / Social

SOC is your resistance to being manipulated.

SOC is also your ability to manipulate, to schmooze. It’s your gab, your social acumen. Social rules are covered in greater detail later in this document.

### Checks and Contests

When a character wants to do something using an attribute they roll 2d6 and add the relevant SCORE. The result of the roll is determined by comparing the roll to a Difficulty Class or DC. This is a “check”. If the character’s check is the same as the DC or higher, they succeed. Often the DC for a check is the passive SCORE of another character.

If two charactes are in direct competition they are in a “contest”. They both roll 2d6 and add their scores. The higher score wins. In the case of a tie, they either tie in the game or if that does not make sense they redo the contest.

#### Additional Effects on Success

Sometimes, skills or weapons will have additional effects triggered “on 6”, “on at least one 6” or “on matching”. This means that if you succeed and the dice you rolled fulfilled the requirement (being a six, both dice matching, etc.) the effect is activated.

“on 6” effects can be triggered twice if you roll two 6s, “at least one 6” effects only trigger once. “on matching” triggers on any set of matching dice rolled.

### Advantage / Disadvantage 

When you have “advantage”, roll an extra d6 for your check and pick two. When you have “disadvantage”, roll another d6, then pick the two lowest rolls. Advantage and disadvantage cancel each other out and are cumulative.

If you somehow have disadvantage twice and advantage four times, you have advantage twice. Roll four dice and pick two.

### Initiative 

AP is used during “initiative”. Initiative is any situation where many characters want to do things at the same time and the order in which things happen is important. Initiative is most often combat, but it can include other time sensitive events like chases or races.

Every character has 3 AP cards.5 The cards say “1 AP” and indicate what character they belong to with a name, a symbol, or both. Most actions cost 1 AP, but you can do a “reasonable amount” of simple things like talking for free.

Some terms:

**Deck**: This is the deck of cards that the DM (or whoever) draws from during initiative. The deck that the whole table uses.

**Discard**: The discard pile for the whole table.

**Hand**: The cards that you have been dealt and are holding on to.

**“Spending” AP**: Cards that have been used or removed that go to the discard and are shuffled back together for the next round’s deck.

**“Losing” AP**: “Lost” AP is not shuffled back into the deck at the end of the round. It must be “regained” either mechanically or automatically at the end of initiative.

**“Interrupt”**: Spend 1 AP, act immediately

When initiative starts all characters pass their cards to the DM. This includes their AP and any other special cards. The DM shuffles these cards together to create the deck. The DM pulls a card from the top of the deck and either deals the card to the character/player that it belongs to or follows the rules on the card.

When a character is dealt a card they can choose to act using whatever cards they currently have in their hand. They can also just hold on to the card. When cards are spent or activated they get placed in the discard.

Any character can interrupt in order to act at any time, doing this costs 1 AP. The round ends when the table deck is empty and everyone who still has AP has had a chance to interrupt to act with their remaining AP.

At the end of a round, cards that have been discarded are shuffled together to create the deck for the next round. Cards that have been lost are not, they are set aside until they are regained, or initiative ends.

This initiative system is intended for combat that is fast and unpredictable.

#### Multiple -> AP -> Costs

Some types of actions have multiple AP costs. The first time you perform the action in a round it costs the first amount, the second time you do it, it costs the second, etc. These costs are connected with arrows, like this: 1->2->3. This does not limit how many times you can perform an action. If you are at the last cost, pay that amount of AP again to do the action.

#### Temp AP and Regaining AP 

“Temp AP” must be spent immediately when it is recieved or it is lost. If you spend no AP for an entire round, regain 1 AP.

#### "Beginning of the Round"

Very rarely, the particular order things happen in the “beginning of the round” will matter. In that case, effects resolve in this order:

##### First, Effect Management

Any already active effects that trigger “at the beginning of a round” happen first. It happens before anything else in the round does. Examples includes taking damage from [poison] or [bleed] or gaining health from [heal]. If you have some effect or condition that causes you to do some sort of roll or contest, do that now.

##### Next, Status Management

Statuses are added or removed now. A point of [poison] is removed, a point of [heal] is removed, anything that would end at the “beginning” of this round ends now.

##### Skills

Some moves and skills can be used “at the beginning of the round”. These must be used after effects and statuses resolve.

### Character Advancement and XP

Characters gain XP by solving problems, navigating difficult situatoins, etc. XP can be used to increase attribute scores or acquire more skills. There are no character levels in Actlite.

#### Increasing Attribute Scores

Increasing a negative attribute costs 1 XP. Increasing a positive attribute costs a number of XP equal to the new attribute score. This means going from 2 STR to 3 STR costs 3 XP. Going from -1 STR to 2 STR costs **1** (-1 to 0) **+ 1** (0 to 1) **+ 2** (1 to 2) **= 4** XP.

Some species or groups have hard limits on attribute scores and/or alternative costs for upgrading some attribute scores.

#### Archetype Tables
 
Characters gain skills by rolling on "Archetype Tables", collections of thematically or mechanically similar skills. Archetype Tables can have attribute score requirements or some other setting-specific requirement. They can also have varying XP costs for rolls, notated similarly to variable AP costs so that the first roll costs X, the second roll costs Y, and all subsequent rolls have an XP cost of Z, notated X->Y->Z. This allows some tables to reward specialization, and some to punish it. If no cost is listed, rolling costs on the table costs 1 XP.

Skills in tables are loosely ordered by desirability. If a player gets a skill they already have by rolling on an archetype table, they get the skill below/before it in the table. If none are below it, they get the first skill above it. A player cannot roll on a table when they have every skill on the table.

# Weapons


Here's a basic weapon, a club:

Club
Tags: pole, one-handed
Speed: 1->2
Attacks: 
- 1d4 B, On 6: inflict [stun]

## Tags

The “tags” are listed right after the name listed. This is where mechanically-significant descriptors are stored. Some skills may require weapons with particular tags, like "range: close" or "hilt". Weapon tags describe how the weapon is handled. There are six main weapon tags, "hilt", "pole", "one-handed" (or "1-h"), "two-handed" ("2-h"), reach and range.

**hilt**: A weapon with a hilt. A “hilt” is a “well-defined” handle or grip which often2 includes some kind of guard to protect the users hand. Swords, knives, and daggers, are hilt weapons, as are patas and katars.

**pole**: Pole weapons. Weapons with a long shaft rather than a well defined grip. Pole weapons include spears, axes, hammers, and of course, all polearms.

**one-handed**: A weapon designed to be used with one hand. If you use two hands on a one-handed weapon, treat your STR as 2 points higher for the purposes of meeting a STR requirement.

**two-handed**: If you try to wield a two-handed weapon with one hand, attack with disadvantage.

**reach**: How many spaces does your weapon reach? If this tag is absent, assume the weapon has reach: 1. If a weapon has [reach: close], you are treated as if you move briefly into the opponents space to attack them. This is often relevant for particular skills.

**range**: Used for ranged weapons.
<!-- disastrously, in the currently existing weapons a lot of weapons use "range" when they should be using "reach". TODO: fix that -->

Tags can be combined to accommodate unusual weapons like “hand-and-a-half” a.k.a. “bastard” swords or [this](https://www.youtube.com/watch?v=rHWGp5lGUNY) [thing](https://swordsantiqueweapons.com/s1866_full.html). 

## Requirements

Not satisfying a weapon's requirements causes you to attack with disadvantage.

## Speed

The “Speed” of a weapon is the AP cost of an attack with the weapon. If the weapon has multiple costs separated by arrows, you pay the first cost on your first attack with the weapon in a round, the second cost on your second, etc. If you are on the last listed cost, pay that cost again to attack again. Attacking three times in one round with a weapon with the cost “1->2” costs 5 AP.

## To-Hit

The score you add to an attack check with this weapon.

# Hexes 

<!-- The original posts are [here](https://actlite.substack.com/p/hexes-part-1-the-rules) and [here](https://actlite.substack.com/p/hexes-part-2-invocations).  -->
<!-- Really this should just be in a list at the end. -->

Hexes are the foundation of “scrivening”, a magic system relying entirely on written representations. Those who write hexes are “scriveners”. It is the most prominent magic system in the upcoming setting. This is not the only magic system that would be compatible with Actlite, and it is not the only magic system that I plan on making.

Hex magic is a ~low, ~hard magic system. It’s not for everyone. It is built for the type of player that wants to tool around directly with magic, finding clever or unexpected uses, interactions, and effects.3 This system is an example of “opting-in” to complexity, which I’ve written about before.

## Lore

Hexes are symbols used by scriviners to directly access, manipulate, and utilize abstract concepts. By manipulating these symbols, scriveners cause tangible effects in the world around them. Hexes can be subjected to any number of alterations, transformations, and modifications. Some of these operations don’t fundamentally change how the hex works, some do. Different scriveners tend to write hexes in slightly different ways, but they are all accessing the same concepts.

Scrivening uses a combination of written symbols and cognition. [independent] hexes can handle cognition on their own, the scrivener handles the cognition for any other hex. Making a hex [independent] is difficult and requires a lot of modifications and transformations. Because of this, studying an [independent] example of a hex is a terrible way to try to learn the hex.

## Learning Hexes

The easiest way to learn a particular hex is to study it along with some explanation or guidance from the author of the hex. This is one of the many reasons scrivening is a fractured and secretive art. The primary method of teaching someone a particular hex involves giving them access to your hexes directly, putting yourself at risk.

The typical way to learn hexes is to discover them for yourself using the methods or protocols of the relevant school or tradition. Sometimes this means feverish study, sometimes this means clear-headed meditation.

### Mechanics

You can try to learn individual hexes by studying the hexes themselves or you can roll on a hex archetype table. This magic system does not hand players a great big catalog of spells to choose from. Every character should end up with a unique set of hexes that they have to learn to utilize effectively. You are meant to improvise with what you get and use your hex library to write your own signature combinations.

#### Learning Combined Hexes

When you succeed in learning a hex that is composed of multiple hexes, you learn every unknown hex in the combination. The DC to learn a combined hex is +3 for every hex in the combination.

Studying a hex combination takes an hour per hex. You can only attempt to learn a given hex once per day. You cannot study [independent] hexes.

## Hex Activation 

When a hex is destroyed it is activated. When it is activated, it is destroyed. If it is activated while some effect requirement is not met, it is destroyed. “Destroyed” includes smudged to illegibility, the medium that it is written on is torn, etc. 

## Writing and Casting Hexes 

A character can write 3 + WIL hexes, this capacity is reset after every rest. A character can maintain 3 + WIL hexes at a time. If a character writes another hex while they are maintaining as many as they can, the olest hex is destroyed.

Each hex can be modified by up to 3 + WIL [modifier] hexes.

Once written, a hex remains usable until you sleep or until 24 hours pass, whichever happens first.

To write a hex during initiative you have to spend 3 AP for the hex and 1 AP for every modifier.

Many hexes have some kind of activation condition. Often this condition is some action the character might take, like attacking. In these cases you don’t have to pay AP to use the hex. If you want to search for an already written hex you do not already have in your hand and then activate it, pay 1 AP.

<!-- Many of these mechanics are currently unused, so their rules are commented out. -->
<!-- ### [durable] hexes

Durable hexes are not destroyed upon activation. These are often written on a durable medium or some kind of focus like a staff, gloves, robes, or even as a tattoo. If a hex does not have the [durable] tag it is destroyed when activated. [durable] hexes often have casting DCs.
 -->
### [modifier] Hexes

[modifier] hexes can be combined with other hexes. If one hex in the combination is activated, all are. [modifier] hexes do not affect individual hexes within a combination, they affect the whole combination.

### [independent] Hexes

Independent hexes do not lose power over time and are not bound to their author. As a result, effects that target the author do not work. 

## Additional Context

Individual hexes might override any rule listed above. For example, many [modifier] hexes can be added to hexes you did not write.

Hexes can also impose additional restrictions, requirements, or costs. For example, taking extra time to create, having unique costs for creation or activation, or only being compatible with certain hexes.

### [durable] Casting and Hex Tables

[durable] hexes can be written into a “hex pallete”. Hexes can be built from combinations of hexes in the same table and immediately cast without the caster having to write the hex down. Diegetically, a hex “table” might be called a pallete, a matrix, or something else depending on the tradition or school.

[durable] hexes often come with additional or alternative casting requirements. Some hexes can only be cast as [durable] hexes.
[independent] Hexes

To make a hex [independent], a scrivener must attach a [modifier] that consists of two parts.

The first is the “key”. The “key” is the first step in breaking the unique connection between scrivener and hex. It varies from person to person and from hex to hex. The writer must figure out the unique key for each hex they cast, they cannot use someone else’s.

The second part is a “hex signature”. This is a unique hex that you will use every time you make a hex [independent]. The signature does not, on its own, identify you. if someone sees your signature they won’t necessarily know it is yours. However once they do know, they will recognize the signature in every [independent] hex you write. You cannot change your signature.

Two people writing the same non-[independent] hex will write nearly identical hexes. Once they make their hexes [independent] they have to leave distinct signatures. Unless steps are taken to obfuscate the contents of the entire hex, the signature is obvious. The process of making a hex [independent] often means adding a large number of alterations that make it hard for other scriveners to learn the hex, but reading it remains relatively easy.

Some hexes can be made [independent] relatively easily. For some hexes the process is very difficult or costly. Many hexes (especially powerful hexes) cannot be made independent through any known means. If a hex is not [independent], it is bound to an author and follows the usual casting rules

### Invocations

Invocations are [independent] hexes written on long and narrow strips of material. Most often this is paper. Invocations are by far the most common type hex. Many people never come into contact with hexes, most that do only come in contact with invocations. Invocations typically have relatively minor effects. Invocations are almost always activated by tearing the medium they are written on.

Invocations are almost always [independent] so that they do not lose potency. Additionally, [modifier] hexes that harm the author are very easy to write, so any sane scrivener wouldn’t part with a hex without making it [independent] first.

Some of the reasons for the format of the invocation is practical. A long slip of paper is easy to fully rip in half, guaranteeing activation. They are easy to tear with one hand. This is especially useful for weapon invocations, where the invocation is wrapped around either the handle or the hand wielding the weapon. Prayers are written in a similar format.