---
title: Sixtem
---

These are the actlite rules. They are very condensed, there are no examples, there is little clarification. This doc will be continuously edited and updated as the rules for actlite are revised. I am doing it this way because having a longer more complete rules document slows the rate at which I can make dramatic and ill-advised changes. Think of this as a quickstart ruleset.

## Characters

Character sheet for a "baseline adventurer":

**HEALTH: 3:9** 

**DEFENSE: 6** 

**MOVEMENT SPEED: 4**

| ATTRIBUTE      | SCORE |
| -------------- | ----- |
| STR(ENGTH)     | 0     |
| AGI(LITY)      | 0     |
| DEX(TERITY)    | 0     |
| CON(STITUTION) | 0     |
| PER(CEPTION)   | 0     |
| SOC(IAL)       | 0     |

### Health

Character health is tracked as X:Y where X is standard health and Y is critical or "crit" health. When a character runs out of standard health all subsequent damage reduces crit health. When a character runs out of crit health they are either killed or, if you are using more forgiving death rules for player characters, they are "downed".

Every point of CON gives you 1 extra crit health and 2 extra standard health.

### Defense and Movement Speed

Moving costs 1 AP and you move a number of spaces equal to your MOVEMENT SPEED. When an enemy attacks you they roll a check against your DEFENSE, more on that later.

## Scores

A character's attribute scores are added to rolls, checks, and modifiers as well as the "passive" score. A character's "passive" score for a given attribute is 6 + SCORE. The SCORES a character can have are not limited to what is on the default character sheet.

### Missing Scores, [special] scores

If you're asked about a score you don't have, your score is 0 unless the score in question has the \[special] tag. If you don't have a \[special] score you fail any check, contest, or roll related to that score. The \[sp] tag is a shorter version of the \[special] tag. MEDICINE is not a \[special] score but PYROMANCY is.

#### "Standard" Scores

"Standard Scores" are a convention for non-[sp] scores that are important for the current setting. This is just a convention, not a strict rule. Some settings might emphasize a TECHNOLOGY score, others might not use that score at all.

## Checks and Contests

When a character wants to do something that they might fail at, they roll 2d6s and add the relevant SCORE. The result of the roll is determined by comparing the roll to a Difficulty Score or DS. This is a "check". If their roll is the same or higher than the DS, they succeed.

If two charactes are in direct competition they are in a "contest". They both roll 2d6 and add their scores. The higher score wins. In the case of a tie, they either tie in the game or if that does not make sense they redo the contest.

"Checks" are compared to a DS which is often the passive attribute score of another character. Most rolls, including attacks, are checks. 

## Crits and More

If a character rolls in a check or contest and the they succeed, they check the face values on the dice they rolled. They may have skills or effects that are activated on one of three "critical rolls" or die combinations. These are listed below

**Full Crit**: Rolling two 6s.  

**Matching Crit**: Rolling two matching face values.  

**Half Crit**: Rolling at least one 6.  

An example of one of these effects is a character who inflicts the \[bleed] condition on half crit when dealing \[Slicing] damage. Notice that rolling a  Full Crit activates both the Half Crit and Matching Crit conditions.

There is one condition that can be activated when a character fails, the Total Failure.

**Total Failure**: Rolling two 1s.  

Getting a Full Crit when attacking always means dealing 1 more crit damage. Otherwise, rolling a Full Crit means succeeded at your task as well as you could have. Likewise, rolling a Total Failure means you did as badly at the task as you could have. The effect of these dramatic successes and failures is up to DM discretion. Not all checks or contests will involve a great distinction between success and dramatic success. 
<!-- Why have all of these special terms and conditions to check? Differing probabilities! -->

<!-- ### You Can Probablity Skip This Section  

A roll of two d6s can resolve in 36 different ways, 36 combinations of dice. I will refer to these as "cases". Assuming a roll of 7 passes (most common DC), 21 of these cases pass (sum to >=7).

| Condition | Passing Cases | Percentage of Passing Cases | Percentage of all Cases |
| --- | --- | --- | --- |
| Crit | 1 | 4.8% | 2.8% |
| Crit Fail | 0 | 0% | 2.8% |
| Matching | 3 | 14.29% | 8.3% |
| Half Crit | 6 | 28.6% | 16.7% |

Didn't verify this. Winged it. Might be wrong. -->

### Crit and Crit Fail

Crit Fails are maximally bad. You did as badly as you could have done (~3% probability).  

Double 6s are good. You did as good as you could have. If this is an attack roll, do 1 extra crit damage on top of any other effects. 

## Initiative and AP (Action Points)

AP is used during "initiative". Initiative is any situation where many characters want to do things at the same time and the order in which things happen is important. Initiative is most often combat, but it can include other time sensitive events like chases or races.

Ever character has 3 AP cards unless otherwise noted. The cards say "1 AP" and indicate what character they belong to with a name, a symbol, or both. Most actions cost 1 AP, but you can do a reasonable amount of simple things like talking for free. Some characters have skills or specializtions that allow them to have extra AP cards. These often have use requirements, like the Bruiser skill which grants 1 AP that can only be spent on an attack costing 2 or more AP.

When initiative starts all characters pass their **table sets** to the DM. In addition to AP, the table set can also include special ability or effect cards. The DM shuffles the table sets together to create the **table deck**. The DM pulls a card from the top of the deck and either deals the card to the character/player that it belongs to or follows the rules on the card. When a character is dealt a card they can choose to act, spending however many cards they currently have in their **hand**. They can also just hold on to the card, adding it to their hand. When cards are spent or activated they get placed in the **table discard**. Any character can **interrupt** at any time, spending 1 AP to act immediately. The round ends when the table deck is empty and everyone who still has AP has had a chance to use interrupt. Acting at the end of a round requires using interrupt.

Cards are **discarded** or **spent** are shuffled together to create the table deck for the next round while cards that are **trashed** or **removed** are not shuffled in at the end of the round and return to the table set after initiative ends completely unless otherwise stated.

**Table Deck**: This is the deck of cards that the DM (or whoever) draws from during initiative. The deck that the whole table uses.  

**Table Discard**: The discard pile for the whole table.  

**Table Set**: Each character's personal set of cards that they add to the table deck when initiative starts.  

**Hand**: The cards that you have been dealt and are holding on to.  

**Discard/Spend**: Cards that have been used or removed that go to the discard and are shuffled together next round to make the table deck.  

**Trashed/Removed**: Cards that have been used or removed and do not get shuffled back in every round.  

**Trash**: The trash pile for the whole table.  

If you want to act, speak up before the DM moves on! Remember, you can spend 1 AP at any time to act immediately.  

### Multiple->AP->Costs

Some types of actions have multiple AP costs. The first time you perform the action in a round it costs the first amount, the second time it costs the second, etc. These costs are connected with arrows, like this: 1->2->3.

#### AP Shenanigans: Temp AP, Losing AP, Gaining AP, the "Wait" action

"Temp AP" must be spend in the same round it is recieved. If you do nothing for an entire round, regain 1 AP from the trash if you have lost any.

### "Beginning of the Round"

Sometimes the *particular* order things happen in the "beginning of the round" will matter. In that case, they resolve in this order.
 
#### 1. Effect Managment

Any *already active* effects that trigger "at the beginning of a round" happen first. They happen before anything else in the round does. Examples includes taking damage from \[poison] or \[bleed] or gaining health from \[heal]. If you have an effect active that causes you to do some sort of roll or contest, do that now.

#### 2. Status Management

Statuses are added or removed now. A point of \[poison] is removed, a point of \[heal] is removed, anything that would end at the "beginning" of this round ends *now*.

### 3. Skills

Some moves and skills can be used "at the beginning of the round". These must be used **after** effects and statuses resolve.