---
title: Social
---

The social rules in their entirety. Fuck.

## SOCIAL Rolls

Now for the least important part of playing a TTRPG, interacting with other people. This system is designed to allow a characters skills and stats to *augment* their social actions. The emphasis is not on getting good rolls, but on saying or doing the right thing. Rolls are used to express a particular character's social talents, but they don't replace the content of what the character says or does.

A GM can use a check to determine success if they really do not know whether a given social action should or shouldn't work on some character, and neither a success nor failure would be especially interesting. Even in this case, difficulty should be determined contextually. Grading numerical difficulty for a social interaction is generally difficult. A GM cannot prepare beforehand for the things a player will do or say, so DCs have to be set on the fly. Sometimes they are set incorrectly or something breaks. In this case, ignore the system/roll and do whatever is the most sensible/interesting/funny.

Social skills are divided into two sets: communicative skills and perceptive skills.
communicative skills include persuasion, deception, and performance. Perceptive skills include sensing motives, detecting deceit, and gaining insight into another character's emotional state.

### Communicative Skills, Bias, and Reputation

| Score | Name              | Description                                                                                                                                                                                                                                                             |
| ----- | ----------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 6     | Revered           | You are seen as almost otherwordly, beyond reproach.                                                                                                                                                                                                                    |
| 5     | Loved             | You are set apart from others, distinctly trustworthy, valued, and important.                                                                                                                                                                                           |
| 4     | Admired           | You are seen as an example to be followed, people will give your words great weight. They will go out of their way to help you out.                                                                                                                                     |
| 3     | Trusted           | You are trusted and valued. People will go out of their way to help you.                                                                                                                                                                                                |
| 2     | Well-Liked        | You are liked quite a bit. People are willing to help you out. They want to see you do well.                                                                                                                                                                            |
| 1     | Liked             | You are liked. People want to talk and barter.                                                                                                                                                                                                                          |
| 0     | Neutral           | People don't think much of you one way or another. They have the time to talk.                                                                                                                                                                                          |
| -1    | Disliked          | People will give you bad deals in trade. They do not particularly want to talk to you. They do not want to barter.                                                                                                                                                      |
| -2    | Strongly Disliked | People do not want to talk or trade. They want you to go away.                                                                                                                                                                                                          |
| -3    | Loathed           | You are a pariah.  A group might throw you in jail, an individual might do you harm opportunistically. People will actively try to get rid of you.                                                                                                                      |
| -4    | Hated             | You will be attacked. If someone is attacking you, they will be given help.                                                                                                                                                                                             |
| -5    | Despised          | You will be attacked on sight. There is probably a bounty on your head.                                                                                                                                                                                                 |
| -6    | Reviled           | You are vilified and reviled. Your name, face, and terrible actions are known. A group will send paid assassins and soldiers after you. An individual will go to great lengths and take on great risk and personal cost in order to do as much harm as possible to you. |

The framework for setting a DC for a given social roll and the framework for reputation management are the same and they can be used in combination. Both systems share the same table of scores with rough characterizations of what each score "feels" like.

The scores range from -6 ("Reviled") to +6 ("Revered"). These scores can be used by a GM to easily keep track of relationships and attitudes. They are also mechanical modifiers. If a character is at -2 ("Strongly Disliked") with some group or individual, you treat their social roll as lowered by 2 (or you can just raise the DC by 2).  

You can use these scores to set a sort of "default" attitude or bias for NPCs. The kindly innkeeper in a small peaceful town might treat every new person at around +2 ("Well-Liked"). The sneering guards in front of a keep might treat everyone at -2 ("Strongly Disliked"). Another traveler on the road just trying to get to where they're going might be at -1 ("Disliked") just because they really don't want to stop and chat. The same traveler might, if you help them out, switch to +1 ("Liked").  

The purpose of social rolls is to be able to, in a given interaction, change the way people perceive you or interact with you. Remember that rolling checks with the SOCIAL score does not replace the content of what a character does or says, but just augments it. If a player passes the DC, treat their interaction as happening at 1 point higher than it would be otherwise. If the player exceeds the DC by more than 3, you can treat the interaction as being at 2 points higher than it would be otherwise. 

Say a player character is in a town in which they are at -3 ("Loathed"). Typically, this would mean that they are treated as a pariah, people are unwilling to talk to them and will actively attempt to get rid of them, they might be thrown in jail on made up charges. Guards will not come to their aid. If they are very charismatic they may be able to walk into a shop, attempt to talk the owner into selling them something and succeed by 4 on a roll. The shop owner thinks that the player character really doesn't seem quite so bad, he thinks that maybe he is misremembering something or getting this person confused with someone else. He is still wary, however. He still treats the character as -1 or "Disliked", he will tend not to want to barter, and he'll want to get through the interaction quickly. Similarly, a guard treating everyone at -2 might be persuaded to relax a bit and just talk to the player character on neutral terms (-2 -> 0).  

Of course, there are plenty of things besides social interaction that might raise or lower someone's opinion of you, and if the content of what a player character said is something that another character would naturally agree with or go along with, then no roll is necessary. Remember that the good will from one positive social interaction does not last forever. Actions will tend to have a greater effect for longer than words. If you just stabbed someone, you are not going to be able to smooth that over with your wit and charm, you do not even get to roll. 

The table with specific characterizations is useful, but it can be boiled down to some rules of thumb. 0 is neutral. From +1 to +3 the character is favored. Persuasion, information gathering, and bartering will be easier. People give you the benefit of the doubt. From +3 to +6 people will go out of their way to help you, they will likely come to your aid in combat or follow you into combat. From -1 to -3 people dislike you and generally do not want to have anything to do with you. -4 to -6 is when you start seeing a lot of unprovoked violence.

This framework is largely for the benefit of the GM, to allow them to easily keep track of attitudes and relationships and to quickly create DCs and resolve rolls in a way that rewards the skills of the player as well as the skills of the character. 

There are several different ways a GM can deal with this system in game. The system can be player-facing, that is to say, you could tell your players their numerical reputation among different groups or numerical values for the attitudes of various characters (along with descriptions). I do not recommend this. You could gate numerical information behind something like a good insight roll. This is fine, but even in this case you should lean on qualitative descriptions of how some character treats a player character. You can also keep the entire system completely to yourself, as a useful tool for the GM to structure descriptions and interactions. In this approach players do not get to actually know numerical values and you never have to reveal or justify movements in numerical values. This is probably your best bet. In this case the framework is still useful for figuring out how much the charisma of the character has helped the efforts of the player.

### Social Perception

"Social perception" is used here to refer to skills that allow you to roll to sense motives, detect deceit, and gain insight into another character's emotional state. It's important here to establish when *exactly* these skills are used and checks are made.

When a player asks a question that would fall under "social perception" about another character, they should first be given a superficial description of the character and their apparent emotional state. If the character in question seems to be at ease, the GM should just say so. This is true even if the character in question is only pretending to be at ease, but plans to attack or betray the player's character. It does not take a roll to be told that someone yelling and brandishing a knife is probably somewhat unhappy. The rules and skills for social perception are not meant to cover the superficial. These rules are for attempts to read another character. Social perception rolls are very similar to other character conflicts, they can be either a check or a contest.

### Social Checks

When the roll is a check, the DC will likely be a default DC of 6 + SOCIAL (and/or relevant skills). If you are trying to read a character who is is lying the DC will be set by their initial attempt to lie, which will have been a check + SOCIAL (and/or relevant skills) against your passive social perception. If they attempt to lie and fail this check, then whatever they said will be described as highly suspicious or likely a lie. If they succeed in their initial check, but you pass their DC when you attempt to read them, you will notice that something seems wrong, or suspicious, or you'll notice strange nervous habits.

Social perception rolls are almost always checks. If you are lying to someone, you perform a check. If they are trying to figure out if you are lying, they perform a check. If someone is trying to convince you of something and you think they might be lying, you perform a check. 

#### Social Check Resolution

In the case of a tie, resolution is the same as any other check. Defender wins. Otherwise there are four possible outcomes. 

***If you pass the check more than 3, Complete Success:***

You read the defender like an open book. You get a full answer to whatever question you were asking, or as full an answer as you could get from watching someone. They crumble at your gaze. Maybe they are so caught off guard that they fumble and make an embarrassing mistake, mentioning something they should not have.

***If you pass the check by 3 or less, Moderate Success:***

You get some insight into the question you were asking. If you are trying to see if someone is lying, you'll know that they're certainly not telling the whole truth, that they are actively misleading you. If you're trying to get insight into someone's emotional state, you get a good idea of how they are feeling. You might be able to tell that someone is distressed and trying to hide it. This is a pretty good read of someone, and they do not know that you know anything.

***If you fail the check by 3 or less, Moderate Failure:***

You have no answer to your question at all and the person you were attempting to read knows the vague shape of the question you asked or that you have a question. If you were trying to figure out if someone was lying about a specific claim they might know that you don't trust them or that you suspect them in some way. Otherwise, you might just be staring and it's weird.

***If you fail the check by more than 3, Catastrophic Failure:***

God have mercy on your soul. You completely give yourself away, your interests and your question are written all over your face. If you are trying to catch a lie, not only is it clear what exactly you think is being lied about, it's clear that you have *no* idea if the defender is lying. Maybe you scoffed at a specific claim, maybe you blurt out "But the stone of Macguffin!" at exactly the wrong time. Your face is very red.

### Contests

Contests are far rarer than checks. Social perception contests happen in contexts where it is understood that both parties are trying to advance their own interests and, if not outright lying, being very selective with the truth. Some examples of this would be a tense negotiation, an official dinner of ambassadors whose states are on the brink of war, a game of poker, spies meeting to trade secrets while not revealing their true intentions. In these cases checks would be happening simultaneously anyway, and the information that someone might doubt what you are saying or that they might not be telling the whole truth wouldn't be very meaningful.

Contest Resolution is just about the same as check resolution. The difference between the rolls of the two characters determines which character succeeds and which fails, and to what degree. This success and failure are captured by the same event. For example one character might give away information they shouldn't have, which captures both the success of one character and the failure of another.

Ties are just ties, a staredown, a tense silence. If your group prefers, ties can be resolved in the normal way for a contest: win goes to the higher modifier, if that's a tie, it's a tie in game, if that makes no sense, do it again.