---
title: "Tactile"
---
## Weapon Rules

Some weapons deal flat damage, some (often large weapons) roll for damage. Most of the expression of skill and weapon uniqueness come from effects/conditions/crit damage triggered by the attack roll.

### Weapon Speeds

- Light: 1

- Medium: 1->2

- Heavy: 2, 2->3

- Giant: 3

### Attack Damage Types

These tags describe the type of damage that the weapon does. 

There are three major types of damage. They are: B for "Bludgeoning", [P] for "Piercing" and [S] for "Slashing". There are also sub-types like [Severing], [Slicing], and [Picking]. [Severing] counts as the more generic [S], but [S] does not count as [Severing]. The damage sub-type will share the first letter of the more generic damage type. This has worked so far because there are very many words in english and they are conveniently placed. I am not afraid to resort to attic greek or something to keep this stupid system working.

Some weapons do two types of damage only for the purposes of armor damage reduction, only the first gets to be used for skills (that's bad). This looks like: B/[P]  

#### Some common damage subtypes: 

**\[Slicing]**: What a saber does. Long fast drawing cut, often with a curved blade.  

**\[Severing]**: What an axe does. A chopping motion.  

**\[Picking]**: What a warpick does.  
  
#### Unused damage types:  
  
**\[Bashing]**: Not sure what sort of blunt weapon would blunt in a way that is different enough to justify this damage type, but it is there.  
  
**\[Pickling]**: What a warpickle does.  

#### Don't

**\[Striking]**: Don't do this.

**\[Stabbing]**: Please don't do this.

<!--**\[Poking]**: Silly.  

**\[Bonking]**: Even more silly. -->
### Weapon Damage

https://docs.google.com/spreadsheets/d/1F0dQgrzN-6pcHPDZExC7pSu5xIdd3tqt3Z-oVc8CK0g/edit?pli=1#gid=437119287

### Weapon Switching

Dropping a weapon is a free action. Putting a second hand on a one-handed weapon is a free action. Removing a hand from a weapon or any other minor adjustment is also a free action.
Drawing a weapon costs 1 AP. Picking a weapon up off the ground costs 1 AP and you're \[vulnerable] while you're doing it, you can be interrupted with an attack while you duck down to grab a weapon. Putting a weapon away costs 1 AP.

### Being Below a Weapon’s Requirements

If you’re below a weapon’s requirements, you get no score based damage scaling (+SCORE) when using that weapon. Your max  To-Hit modifier is 0 with that weapon. For every point you are below a SCORE requirement, halve the damage you do rounding up. If you would do 1 damage you cannot wield the weapon.

<!-- ### Two-handing a \[one-handed] weapon, one-handing a \[two-handed] weapon

If you’re 2 STR above the requirements for a \[two-handed] weapon, you can effectively wield it with one hand. If you use two hands on a \[one-handed] weapon, raise your effective STR with the weapon by 2. 

im not sure that this is a good rule, it seems like it should be broken up into a skill for the very strong and a benefit for those small enough to fit two hands on a one handed weapon.
 -->

### Throwing a spear or a dagger without a specific \[thrown] move

For every point you are below requirements for the weapon, halve the range. 
Throwing a spear or dagger costs 2 AP, uses PER(CEPTION) to hit, has no damage scaling, 3 + AGI spaces for range. It does half damage rounded up when thrown.

## Resting and Healing

Here are some differnt healing mechanics I need to test...

**Strict**: Every day you recover 1 crit health if you are missing crit health, or 3 standard health if you are not.

**Under-Die**: Every long rest you roll the largest die that is under your max standard health. If you have 7 standard health, you roll a d6. Crit damage is healed first.

**Dont-Get-Crit**: At a long rest, if you have taken crit damage, recover 1 crit heatlth. Otherwise, recover all standard health. 

## Injury and Death

This part consistently needs reworking.

### Injury

Injuries are unique conditions that typically come with crit damage. Injuries are removed when the character reaches full crit health.

### Dying Instantly or Being Stabilized

If you are reduced to -(Max HP/2) you die instantly.  

If your HP is brought above 0, you are stabilized. If you are stabilized but you haven't reached 6 HP, rest (rolling recovery dice) until you reach 6 HP. If you're brought back to 6 HP or more, regain consciousness.

#### Being Reduced to 0 HP, Being "Downed"

You can have negative HP. You can also stabilize even with negative HP, but you have to reach 6 HP before you regain consciousness.

When a player is reduced to 0 but not killed, they are "down" and they are unconscious. If they are not stabilized, they are unable to take any sort of action besides rolling death checks. They are \[vulnerable].

When a player is downed the DM sets a death DC by rolling 2d6 with no modifiers. The DM does not tell the player the DC. 

On the turn a player is downed and on every subsequent turn, the player rolls a death check and tells the DM their roll. If their roll matches or passes the DC it's a success. If the roll is below the DC, it's a failure. If the roll is a failure, the DM notes by how much the roll failed, DC - roll. This difference will be used to determine the consequence of the failure using the consequence table. Don't make any extra rolls to resolve consequences at this point as other characters might use medicine to improve the outcome, skills might be triggered, etc. Consequences are only resolved if/when the character survives.

3 successes means the character stabilizes at their current HP. 3 failures means they die.

Once they either hit 3 successes or 3 failures, the DM tells them to stop rolling. They are not told whether they died or not or what consequences they might have. They only find out once someone goes to check on their character. 

If you're hit while you're down, take the damage and add a failed death check.

### Consequence Tables

Consequence tables exist to determine what happens if you fail death checks. Different areas might have different consequence tables, the DM might pick a table completely randomly. Different campaigns might prefer harsher or more lenient consequenes. Having many consequence tables and an unknown death DC should make being downed stressful and full of uncertainty, this can increase the stakes while not necessarily increasing the chance that the character dies. Below is a sample generic consequence table and some sample consequences. 

| Failure     | Consequence                           |
| ----------- | ------------------------------------- |
| -1          | \[weak] (1 Hour)                       |
| -2          | \[weak] (8 Hours)                      |
| -3          | Scars, \[frail] (8 Hours),             |
| -4          | Scars, \[frail] (1 Day), Lower 1 Stat  |
| -5          | Scars, \[frail] (2 Days), Lower 1 Stat |
| -6, -7      | Scars, Lame                           |
| -8, -9, -10 | Lose a Limb                           |

#### Consequences

***\[weak]***

-1 STR, -1 CON, -2 to Defense

***\[frail]***

-1 STR, -2 CON, -1 AGI, -3 to Defense

***Scars***

Scars are completely cosmetic and up to DM discretion. The scar might be from the blow that downed the character or they might be from some other large blow received in the same fight. 

***Lower a Stat***

Lower a stat by 1 by rolling a d4 using the following table:

| Stat | Roll |
| ---- | ---- |
| STR  | 1    |
| AGI  | 2    |
| DEX  | 3    |
| CON  | 4    |

***Lame***

Take your first move action as normal. Every subsequent move action is slower by 1 space.

***Lose a Limb***

Determine Limb loss by rolling on the following table. If you land on a limb you do not have at least one of, roll again. 

| Roll | Limb |
| ---- | ---- |
| 1    | Arm  |
| 2    | Leg  |
| 3    | Eye  |
| 4    | Ear  |

## Odds and Ends

Some rules that did not fit nicely into a cohesive category.

### Stealth

Stealth is an AGI check (+STEALTH if you have it) against the defender’s passive perception. It’s a check against a passive score, and that is always 6 + SCORE.

### Grappling

Entering grappling takes 2 AP, it's an attack + AGI To-Hit followed by a STR contest. If the party entering the grapple wins, both parties are \[grappling] but only the defender is \[vulnerable]. Defender can spend 2 AP to trigger another STR contest to try and break free. Defender can do nothing else.

#### Taking a Hostage

Same as above, but the attacker rolls one fewer die on the initial grapple check. They can attack the defender during the grapple provided they have a \[range: close] weapon.

### Fall Damage

Fall damage is a d4 for every 6 spaces up to 25d4.

### Taking 10

You can take 10 minutes to work at something (that you can try repeatedly at where there is no cost for failure) to treat your check as a 10 + relevant modifiers.

## Common Status Effects

### [bleed]

At the beginning of the round, take damage equal to the amount of [bleed] you have. [bleed] does not go away on its own and must be removed.

### [curse]

For every point of [curse] a character has, they suffer -1 to all rolls. 1 [curse] is removed at the beginning of every round.  
Points of [curse] are often inflicted so that the attacker might use up the [curse] points on a defender in order to cast a specific and sometimes longer lasting curse.

### [frail]

Frail causes you to take double damage from poison and bleeding and lowers max CON by 2 until [frail] is removed.

### [heal]

At the beginning of the round, increase your HP by the amount of [heal] you have, then remove 1 [heal].

### [poison]

At the beginning of the round, take damage equal to the amount of [poison] you have, then remove 1 [poison].

### [vulnerable]

If attacked while [vulnerable], the enemy gets to roll an extra d6 to hit and rolls double their damage dice.
Many skills and situations inflict the [vulnerable] status, for example: being distracted, blinded, grappled, or unaware.

<!-- # Not Really Core!

## Encumbrance and Rations

Encumbrance is measured in encs. Encs are a combined measure of weight and unwieldiness. Most weapons are 1 enc. A \[heavy] weapon is 2 encs. A days worth of food and water is 1. 3 small items, like a book, a dagger, and some bandages together take 1 enc. Negligible items like quills and needles don't take up any encs, unless the DM determines you are carrying "way too many".  

Players must describe and account for how they are moving their things. They take "reasonable" penalties for impractical methods. If they tie a bunch of swords together and then hang that off of their neck, they will have a hard time stealthing. If they fall over while wearing the described necklace of dangerous wind chimes they're going to have a bad time.

### Storage Spaces, The "Personal" Space and Bags

"Storage space" is used to broadly refer to any place you can put things. Each storage space you have can be thought of as a source of a max encumbrance and a source of an \[encumbered] threshold. Most of the time you will have two storage spaces: 

- Your "personal" space, which includes anything you're carrying that isn't itself a storage space. Most often this would be your weapons and armor. 

- Your bag. This is most often some kind of backpack.

You have a personal \[encumbered] threshold. This is used for the weapons and armor you are carrying without a bag.
Your personal \[encumbered] threshold is 3 + STR. Your personal max encumbrance is 6 + STR encs.

The primary use of a bag is to give you more \[encumbered] thresholds and to change your maximum encumbrance.

Bags have varying \[encumbered] thresholds and max encumbrances. If a bag does not say it has an \[encumbrance] threshold, then it never makes you \[encumbered]. This is common for small bags that don't have a max encumbrance high enough to be able to encumber, or bags that are designed not to encumber.

Removing a bag is 2 AP.

Searching a bag is 2 AP.

### The \[encumbered] Threshold and Maximum Encumbrance

If you are past any encumbrance threshold in any storage space, you are \[encumbered], you have the \[encumbered] status.

The \[encumbered] status lowers your move speed by 1. Your Defense is lowered by 3. Additionally, take a -1 to all AGI checks.

If you aren't wearing heavy armor but you're carrying enough in your bag to pass the bag's encumbrance threshold, you are \[encumbered]. Less obviously, this also means that if you are past your personal encumbrance threshold (most likely from carrying weapons and wearing armor that are too heavy for you to move freely with) but you are not past your \[encumbered] threshold for your bag, you are still \[encumbered].  

In order to avoid passing an \[encumbered] threshold you likely want to spread the weight around multiple storage spaces, keeping under all of their \[encumbered] thresholds, or you might want to just put everything in a bag so that in a fight you can take it off quickly and not be \[encumbered].

You cannot carry more encs in total than your single highest max encumbrance score. This does not mean that having one storage space where you can carry 8 encs means that you must be able to carry 8 encs in every storage space, it just means that all together you can't carry more than 8 encs.

Unless otherwise specified, you can only use one bag at a time. If some mechanic allows you to use multiple bags, you cannot carry in total more than your highest max encumbrance from a single source, though you can move encs around to try to avoid the \[encumbered] status effect.

Your \[encumbered] threshold and your maximum encumbrance can be affected by status effects or skills, but most often they will be affected by the bag you are using. -->

