---
title: "Tactile Bare"
---

## Weapon Rules

Many weapon damage amounts are flat, with a lot of expression of skill and weapon uniqueness coming from effects/conditions/crit damage triggered by the numbers rolled in successful to-hit rolls.

### Weapon Speeds

- Light: 1

- Medium: 1->2

- Heavy: 2, 2->3

- Giant: 3

### Attack Types

These tags describe the type of attack and are mostly used for skills and effects. The tags are:  

- [whack]: A heavy chopping motion. Axes, hammers, warpicks. Glyph: ▷▶  
- [slice]: A pulling cutting motion. Various curved swords. Glyph: ▶▷  
- [thrust]: A stabbing motion. Spears, estocs. Glyph: ▲

Potential other tags for exotic weapons:  

- [whip]? Maybe [flail]? something like that.  
- [pulling]: For scythes.  

### Attack Damage Types

These tags describe the type of damage that the weapon does. 

-[Bludgeoning]: [B] for short.  
-[Piercing]: [P].  
-[Slashing]: [S].  

Some weapons do two types of damage only for the purposes of armor damage reduction, only the first gets to be used for skills (that's bad). This looks like: [B]/[P]  
  
### Weapon Damage

https://docs.google.com/spreadsheets/d/1F0dQgrzN-6pcHPDZExC7pSu5xIdd3tqt3Z-oVc8CK0g/edit?pli=1#gid=437119287

### Weapon Switching

Dropping a weapon is a free action. Putting a second hand on a one-handed weapon is a free action, same for removing a hand from a weapon or any such minor adjustment, if in doubt TTYGM.
Drawing a weapon costs 1 AP. Picking a weapon up off the ground costs 1 AP and you're \[vulnerable] while you're doing it, you can be interrupted with an attack while you duck down to grab a weapon. Putting a weapon away costs 1 AP.

### Being Below a Weapon’s Requirements

If you’re below a weapon’s requirements, you get no score based damage scaling (+SCORE) when using that weapon. Your max + To-Hit is 0 with that weapon. For every point you are below a SCORE requirement halve the damage you do rounding up. If you would do 1 damage you cannot wield the weapon.

### Two-handing a \[one-handed] weapon, one-handing a \[two-handed] weapon

If you’re 2 STR above the requirements for a \[two-handed] weapon, you can effectively wield it with one hand. If you use two hands on a \[one-handed] weapon, raise your effective STR with the weapon by 2. 

### Throwing a spear or a dagger without a specific \[thrown] move

For every point you are below requirements for the weapon, halve the range. 
Throwing a spear or dagger costs 2 AP, uses PER(CEPTION) to hit, has no damage scaling, 3 + AGI spaces for range. It does half damage rounded up when thrown.

## Resting and Healing

For every 6 Max HP your character has, they get one recovery die. The recovery die is a d6. At every long rest (a rest of 8 or more hours), you regain all of your recovery dice. For every hour you rest, you can choose to use one recovery die, rolling it and adding it to your health.

TODO: INJURY, DEATH