---
title: About
---
<!-- ### What is all this?

"Citatel" is the website. It is the public home of "Tactile", the system.  

The "Sixtem" is the use of 2d6 for checks and contests with attributes centered around 0. "Tactile" is that plus all the other rules. There are two reasons for the distinction. The first is that they were written independently, while "Tactile" was being created several different dice, combinations of dice, and attribute mechanics were used. The second more important reason is that "Sixtem" is a fun name and I like it

"Talaje" is the only extant setting for "Tactile". It includes npcs, weapons, skills, etc. etc. You can change it, take parts of it for your own setting, or throw it all out and make something completely unrelated. -->

### What kind of game is this?

The base rules should be flexible enough that they can be modified to make many types of games. That being said, the setting, weapons, etc. presented in this site are used to make a game where the player characters are not inherently special. Player characters follow the same rules and use all of the same mechanics that NPCs use. 

The game is about normal people making their way through a dangerous and fantastic world.  

### Tone and Goals

The world of this game is much bigger than the players and it moves without any concern for them. When players meet a creature there should be no expectation that they will be able to kill it. If players pick a fight they can't win, that's on them. Characters might lose limbs. They might die as a part of normal combat. The game is not built to make players straightforwardly more powerful over time, but that doesn't mean they have no agency. Players have resources to advance their characters. If a player wants more health, they choose to spend their limited resources on health. The same is true for skills. Characters should grow in response to the pressures they face. Characters become better at what they try to do, they do not progress smoothly along a given plan. There are no classes and there are no levels. There is no destination. There are only small people and their unreasonable efforts and goals.

There are skills for fantastic magic powers as well as more mundane abilities such as quickly drawing a weapon, disarming an opponent, parrying a blow, and effective use of a shield. Every weapon has strengths and weaknesses, different weapons have different AP costs, different reach. Some might be better at slashing than piercing. A player should think carefully about what they take with them and what they can do with it. The reason for the great historical variety of weapons is that different designs work better in different contexts and for different purposes. I'd like a game that lets you engage with that dynamic and expands on it with interesting and relatively light mechanics.

In general, the context a character finds themselves in at any point is hugely important. Say you have a very advanced knight-type character with all sorts of skills. He's in heavy armor standing guard. There's a relatively weak early-game assassin character who has specialized in stealth and sneak attacks. The assassin has a long thin dagger meant for slipping through armor. The assassin manages to catch the knight unaware, prepares his strike, and drives the dagger through his neck. The knight is probably dead. In a direct fight the assassin would have no chance at all. This, basically, is how balance is handled (or not handled). The quality of skills, weapons, and character types depend on context and creativity. If you're that knight standing guard, you probably want to invest in your perception, you probably want someone watching your back. In general, you should be thinking about what other people might try, you should be thinking about your vulnerabilities and how you're going to deal with them.

Combat is not orderly. You should be trying to take every advantage you can find. You should be trying to break the game. The flexibility of the system should give you the freedom to engage with combat in whatever way seems fun or interesting to you. You can set up status effects and conditions to trigger very powerful moves, you can dodge and weave around attacks finding an opening for a critical strike, you can use illusion and deception, you can just make an unga-bunga character that wields a club made from a whole tree. This might be a weapon that was never meant to be wielded by a player character, but you have so many Giant Weapon skills that you can use it to completely flatten anything in your path. You could also just talk your way out of a fight or sneak around and avoid the interaction entirely. Set up distractions, traps, bribe someone so you find out your enemies weaknesses beforehand. The way that you deal with situations should be unique to your character and your skillset.

An old wizard beset by bandits doesn't have 10 times as much Health as they do because he's "a high level wizard". He might have less health than they do. However, he has the tools and knowledge to make such an encounter trivial anyway.

There are games that are built to make you feel a lot more powerful than everyone else in the game world, games that are far better suited to playing out the story of a legendary adventurer who went from hunting rats to slaying dragons. This is not that game. This is a game about people exploring dangerous places, taking risks, and beating genuinely bad odds with quick thinking, preparation, and luck.

On top of all this, the game should be relatively rules-light. When rules show up they should add to the tactility of the world not take it away. They should give you more options, they should be easy to improvise and *easy to improvise with*. There should be no superfluous rules for "realism". While there is a baseline of universal rules and mechanics, a player should largely get to choose what specific mechanics they use to interact with the world, whether that's risk-reward mechanics, complex chained effects, AP cleverness, Big Numbers, thinking of the perfect illusion at the perfect time, or social charm. Players aren't restricted to one class or the options in that class, they can combine skills and mechanics in any way they can manage.

These are a lot of goals in this doc. The currently existing game is an attempt at reaching toward those goals. Many of these goals are in a great deal of tension with one another. Let's see how this goes.