---
title: 3. Shopping
execute: 
  echo: false
  output: asis
---

```{python}
import os
from citutils import text_utils_parsers as tu
entities = tu.get_entities(os.path.join("..","..","..","data","entities"), True)
```

## Base Sheets
 
There are currently only a couple to choose from. TODO: add those/that one??. Another problem is that base-sheets really don't fit in the .yamls right now. Given that the .yamls were also going to be extended to be able to deal with tables and the way to do that was uncertain, it seems like this really should prompt a change in how the .yamls work fundamentally! Are both base-sheets and tables things `entity`s?

{{< include ../../p2_content/base_sheets/ataara.qmd >}}

## Backgrounds

None yet exist. There should be premade backgrounds as well as a background-component-selection-process

Backgrounds determine how many flakes (currency) you start with. 

## Starting Gear

### Premade Loadouts

TODO: need some premade loadouts

```{python}
from citutils import entity_text_generators as ge
print("### Weapons \n" + ge.filter_generate_text(entities, "basic, weapon", html_characters = True))
print("### Items \n" + ge.filter_generate_text(entities,"basic, item", html_characters = True))
```

## Starting Skills

TODO: need some skill-paths... potentially i need to generate in smaller chunks, and probably organize these, once the list is more stable

```{python}
print(ge.filter_generate_text(entities, "basic, skill", html_characters = True))
```
 
<!-- ### A Note on Skills and Backgrounds -->
<!-- Consider how your background and the skills you start with might support each other. Picking specific skills for relevance to your background rather than building an optimal character can give your character a lot of interesting moments, especially early on. -->