---
title: "2. Tactile"
---

## Weapon Rules

A weapon has a Speed, a To-Hit, and a set of basic attacks. The speed is how much AP it costs to do attacks with the weapon. The "To-Hit" is what you add to the check you perform when attempting to hit an enemy. This looks like "To-Hit: DEX" or "To-Hit: STR + AGI" or similar. To-Hit and Speed are both shared for all attacks a weapon has, but each attack can have different damage, different damage types, different effects, and different tags. The three basic damage types are (B)ludgeoning, (P)iercing, and (S)lashing.

Let's go through an example. Say the speed of the weapon is (2n1) and the To-Hit is +STR, it has one attack: "1d6+STR (B) swinging: leading]". When attacking with this weapon, you move 2 AP tokens to the 1 space and roll 2d6+STR for your To-Hit check. If that beats your opponents Defense, roll damage (1d6+STR) and tell the GM that the damage type is (B)ludgeoning.

Some skills require attacks with certain tags like eswinging: leading] or they might only effect certain damage types. Some weapons will specialize in attacks of different types types. This captures how a rapier is better for quick piercing attacks than it is for slashes while a giant curved greatsword would be better at heavy slashing moves. A weapon like a rondel dagger (a long dagger with a narrow but thick blade) is able to ignore some armor and do pretty good damage with a piercing attack, but it will be a good deal worse at slashing than a kukri. If you're in the jungle being attacked by big furry creatures, take a kukri. If you're assassinating knights, take a rondel dagger.

### Attack Tags in a More Detail

The two major tag types are \[thrusting] and \[swinging]. \[swinging] has three sub-types. Those three types are \[swinging: following], \[swinging: neutral], \[swinging: leading]. The subtype refers roughly to "the position of the striking surface relative to the hand in a given swing" but this is much easier to understand through some examples.

***[swinging: leading]*** is the easiest to understand. It's a swinging attack where the striking head is ahead of the weapon as in a warpick, an axe, or a hammer. The blade of the axe projects in front of your hand, it is "leading" the swing. These sorts of attack are typically slower and deal more damage. A (S) [swinging: leading] attack would be like swinging a meat cleaver or an axe, the wound from a [swinging: leading] (S) attack will be relatively short but deep. A [swinging: leading] (B) is like an attack with a hammer, a [swinging: leading] (P) attack is like an attacks with a warpick. You can expect to see attacks with any of the three damage types with this tag.

***[swinging: neutral]*** is the middle ground, attacks of this type will be faster than [swinging: leading] but do less damage. This is where the striking surface is in line with the hand as in a longsword (S), a quarter staff (B), or some sickles (P). You'll see (S) and (B) attacks of this type most often. In general (P) damage is less common for [swinging: neutral] attacks.

***[swinging: following]*** is the oddest of the bunch. Attacks of this sort tend to be the fastest and weakest, relying on skills, conditions, or just an overwhelming flurry of attacks for damage. The central example of [swinging: following] is a curved dueling sabre. These attacks will nearly always be (S). You can construct weapons that have (P) [swinging: following] attacks, but they don't make a huge amount of sense. What would a (B) [swinging: following] attack be? Maybe hitting a guy with the scabbard for your saber. Again, not very common. Magic abilities, skills, and exotic weapons can flesh out this category but there aren't many historical examples of [swinging: following] besides curved swords and some glaives.

***\[thrusting]*** includes thrusts with a spear, sword, or dagger. The vast majority of thrusting attacks have the (P) damage type.

<!-- 
***[pulling]*** attacks are rare. They show up in  some hooked polearms or hook swords. They typically do (S) damage and can involve some kind of grapple check.

So rare that they don't currently exist in the typsetting code... and there are no weapons that use the tag yet! So I'm leaving this out for now. 
-->


These tags describe something physical about the weapon, "striking surface relative to swing" or just the motion as in the \[thrusting] tag, but more importantly the tags describe the way the weapon is *used* for the attack. They describe how the attack *feels*, what kind of motion is done in the attack. A slow-ish sword with a slightly curved blade might still be counted as [swinging: neutral] if those are the sorts of attacks the weapon is made for, if that makes more sense for skills, etc. If you want more info about these distinctions and how weapons are made, refer to the [Weapon Creation doc](../../creation/weapon_creation.md).

Other weapon tags are possible, such as the \[pulling] tag which belongs to scythes, some polearms, and hook swords. These are less important, and they don't get their own glyphs, they exist for niche weapons and skills.

<!-- #### An Aside on Notation

Unfortunately, the tag \[swinging: leading] ends up taking about as much space as the rest of the attack despite being on of the less important elements of the attack. When making cards or other reference material we replace these tags with glyps. ▲ for \[thrusting], ▷▷▶ for \[swinging: leading], ▶▷▷for \[swinging: following] etc. These are rendered a little more nicely in pdf reference material. The glyphs should be pretty intuitive, the filled triangle indicates the striking head relative to the swing (or the subjective "aggressiveness" of the attack). -->


### Weapon Switching

Dropping a weapon is a free action. Putting a second hand on a one-handed weapon is a free action, same for removing a hand from a weapon or any such minor adjustment, if in doubt TTYGM.
Drawing a weapon is (1n1). Picking a weapon up off the ground is (1n1) and you're \[vulnerable] while you're doing it, you can be interrupted with an attack while you duck down to grab a weapon. Putting a weapon away is (1n1).

An example: You want to drop your \[two-handed] greatsword, pick up a handaxe from the ground, and draw your dagger. Dropping the sword is free, picking up the handaxe is (1n1), as is picking up the dagger. You've spent 2 AP, and you were \[vulnerable] for a bit.  

### Being Below a Weapon’s Requirements

If you’re below a weapon’s requirements, you get no score based damage scaling (+SCORE) when using that weapon. Your max + To-Hit is 0 with that weapon. For every point you are below a score requirement, drop a damage die. If there is only one damage die left, make it one die smaller. If you get below d4 you cannot wield the weapon at all. 

### Two-handing a \[one-handed] weapon, One-handing a \[two-handed] weapon

If you’re 2 STR above the requirements for a \[two-handed] weapon, you can effectively wield it with one hand. If you use two hands on a \[one-handed] weapon, raise your effective STR with the weapon by 2. 

### Throwing a spear or a dagger without a specific \[thrown] move

For every point you are below requirements for the weapon, reduce range by 2. 
Throwing a spear or dagger is (2n1), uses PERCEPTION and AGI to hit, has no damage scaling, 3 + AGI spaces for range. Drop a damage die from an attack to determine damage and damage type, if there is only one damage die, lower it. 

## Resting and Healing

For every 6 Max HP your character has, they get one recovery die. The recovery die is a d6. At every long rest (a rest of 8 or more hours), you regain all of your recovery dice. For every hour you rest, you can choose to use one recovery die, rolling it and adding it to your health.

## Injury and Death

### Dying Instantly or Being Stabilized

If you are reduced to -(Max HP/2) you die instantly.  

If your HP is brought above 0, you are stabilized. If you are stabilized but you haven't reached 6 HP, rest (rolling recovery dice) until you reach 6 HP. If you're brought back to 6 HP or more, regain consciousness.

#### Being Reduced to 0 HP, Being "Downed"

You can have negative HP. You can also stabilize even with negative HP, but you have to reach 6 HP before you regain consciousness.

When a player is reduced to 0 but not killed, they are "down" and they are unconscious. If they are not stabilized, they are unable to take any sort of action besides rolling death checks. They are \[vulnerable].

When a player is downed the DM sets a death DC by rolling 2d6 with no modifiers. The DM does not tell the player the DC.  

On the turn a player is downed and on every subsequent turn, the player rolls a death check and tells the DM their roll. If their roll matches or passes the DC it's a success. If the roll is below the DC, it's a failure. If the roll is a failure, the DM notes by how much the roll failed, DC - roll. This difference will be used to determine the consequence of the failure using the consequence table. Don't make any extra rolls to resolve consequences at this point as other characters might use medicine to improve the outcome, skills might be triggered, etc. Consequences are only resolved if/when the character survives.

3 successes means the character stabilizes at their current HP. 3 failures means they die.

Once they either hit 3 successes or 3 failures, the DM tells them to stop rolling. They are not told whether they died or not or what consequences they might have. They only find out once someone goes to check on their character. 

If you're hit while you're down, take the damage and add a failed death check.

### Consequence Tables

| Failure     | Consequence                           |
| ----------- | ------------------------------------- |
| -1          | \[weak] (1 Hour)                       |
| -2          | \[weak] (8 Hours)                      |
| -3          | Scars, \[frail] (8 Hours),             |
| -4          | Scars, \[frail] (1 Day), Lower 1 Stat  |
| -5          | Scars, \[frail] (2 Days), Lower 1 Stat |
| -6, -7      | Scars, Lame                           |
| -8, -9, -10 | Lose a Limb                           |

#### Consequences

***\[weak]***

-1 STR, -1 CON, -2 to Defense

***\[frail]***

-1 STR, -2 CON, -1 AGI, -3 to Defense

***Scars***

Scars are completely cosmetic and up to DM discretion. The scar might be from the blow that downed the character or they might be from some other large blow received in the same fight. 

***Lower a Stat***

Lower a stat by 1 by rolling a d4 using the following table:

| Stat | Roll |
| ---- | ---- |
| STR  | 1    |
| AGI  | 2    |
| DEX  | 3    |
| CON  | 4    |

***Lame***

Take your first move action as normal. Every subsequent move action is slower by 1 space.

***Lose a Limb***

Determine Limb loss by rolling on the following table. If you land on a limb you do not have at least one of, roll again. 

| Roll | Limb |
| ---- | ---- |
| 1    | Arm  |
| 2    | Leg  |
| 3    | Eye  |
| 4    | Ear  |

## SOCIAL Rolls

Now for the least important part of playing a TTRPG, interacting with other people. This system is designed to allow a characters skills and stats to *augment* their social actions. The emphasis is not on getting good rolls, but on saying or doing the right thing. Rolls are used to express a particular character's social talents, but they don't replace the content of what the character says or does.

A GM can use a check to determine success if they really do not know whether a given social action should or shouldn't work on some character, and neither a success nor failure would be especially interesting. Even in this case, difficulty should be determined contextually. Grading numerical difficulty for a social interaction is generally difficult. A GM cannot prepare beforehand for the things a player will do or say, so DCs have to be set on the fly. Sometimes they are set incorrectly or something breaks. In this case, ignore the system/roll and do whatever is the most sensible/interesting/funny.

Social skills are divided into two sets: communicative skills and perceptive skills.
communicative skills include persuasion, deception, and performance. Perceptive skills include sensing motives, detecting deceit, and gaining insight into another character's emotional state.

### Communicative Skills, Bias, and Reputation

| Score | Name              | Description                                                                                                                                                                                                                                                             |
| ----- | ----------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 6     | Revered           | You are seen as almost otherwordly, beyond reproach.                                                                                                                                                                                                                    |
| 5     | Loved             | You are set apart from others, distinctly trustworthy, valued, and important.                                                                                                                                                                                           |
| 4     | Admired           | You are seen as an example to be followed, people will give your words great weight. They will go out of their way to help you out.                                                                                                                                     |
| 3     | Trusted           | You are trusted and valued. People will go out of their way to help you.                                                                                                                                                                                                |
| 2     | Well-Liked        | You are liked quite a bit. People are willing to help you out. They want to see you do well.                                                                                                                                                                            |
| 1     | Liked             | You are liked. People want to talk and barter.                                                                                                                                                                                                                          |
| 0     | Neutral           | People don't think much of you one way or another. They have the time to talk.                                                                                                                                                                                          |
| -1    | Disliked          | People will give you bad deals in trade. They do not particularly want to talk to you. They do not want to barter.                                                                                                                                                      |
| -2    | Strongly Disliked | People do not want to talk or trade. They want you to go away.                                                                                                                                                                                                          |
| -3    | Loathed           | You are a pariah.  A group might throw you in jail, an individual might do you harm opportunistically. People will actively try to get rid of you.                                                                                                                      |
| -4    | Hated             | You will be attacked. If someone is attacking you, they will be given help.                                                                                                                                                                                             |
| -5    | Despised          | You will be attacked on sight. There is probably a bounty on your head.                                                                                                                                                                                                 |
| -6    | Reviled           | You are vilified and reviled. Your name, face, and terrible actions are known. A group will send paid assassins and soldiers after you. An individual will go to great lengths and take on great risk and personal cost in order to do as much harm as possible to you. |

The framework for setting a DC for a given social roll and the framework for reputation management are the same and they can be used in combination. Both systems share the same table of scores with rough characterizations of what each score "feels" like.

The scores range from -6 ("Reviled") to +6 ("Revered"). These scores can be used by a GM to easily keep track of relationships and attitudes. They are also mechanical modifiers. If a character is at -2 ("Strongly Disliked") with some group or individual, you treat their social roll as lowered by 2 (or you can just raise the DC by 2).  

You can use these scores to set a sort of "default" attitude or bias for NPCs. The kindly innkeeper in a small peaceful town might treat every new person at around +2 ("Well-Liked"). The sneering guards in front of a keep might treat everyone at -2 ("Strongly Disliked"). Another traveler on the road just trying to get to where they're going might be at -1 ("Disliked") just because they really don't want to stop and chat. The same traveler might, if you help them out, switch to +1 ("Liked").  

The purpose of social rolls is to be able to, in a given interaction, change the way people perceive you or interact with you. Remember that rolling checks with the SOCIAL score does not replace the content of what a character does or says, but just augments it. If a player passes the DC, treat their interaction as happening at 1 point higher than it would be otherwise. If the player exceeds the DC by more than 3, you can treat the interaction as being at 2 points higher than it would be otherwise. 

Say a player character is in a town in which they are at -3 ("Loathed"). Typically, this would mean that they are treated as a pariah, people are unwilling to talk to them and will actively attempt to get rid of them, they might be thrown in jail on made up charges. Guards will not come to their aid. If they are very charismatic they may be able to walk into a shop, attempt to talk the owner into selling them something and succeed by 4 on a roll. The shop owner thinks that the player character really doesn't seem quite so bad, he thinks that maybe he is misremembering something or getting this person confused with someone else. He is still wary, however. He still treats the character as -1 or "Disliked", he will tend not to want to barter, and he'll want to get through the interaction quickly. Similarly, a guard treating everyone at -2 might be persuaded to relax a bit and just talk to the player character on neutral terms (-2 -> 0).  

Of course, there are plenty of things besides social interaction that might raise or lower someone's opinion of you, and if the content of what a player character said is something that another character would naturally agree with or go along with, then no roll is necessary. Remember that the good will from one positive social interaction does not last forever. Actions will tend to have a greater effect for longer than words. If you just stabbed someone, you are not going to be able to smooth that over with your wit and charm, you do not even get to roll. 

The table with specific characterizations is useful, but it can be boiled down to some rules of thumb. 0 is neutral. From +1 to +3 the character is favored. Persuasion, information gathering, and bartering will be easier. People give you the benefit of the doubt. From +3 to +6 people will go out of their way to help you, they will likely come to your aid in combat or follow you into combat. From -1 to -3 people dislike you and generally do not want to have anything to do with you. -4 to -6 is when you start seeing a lot of unprovoked violence.

This framework is largely for the benefit of the GM, to allow them to easily keep track of attitudes and relationships and to quickly create DCs and resolve rolls in a way that rewards the skills of the player as well as the skills of the character. 

There are several different ways a GM can deal with this system in game. The system can be player-facing, that is to say, you could tell your players their numerical reputation among different groups or numerical values for the attitudes of various characters (along with descriptions). I do not recommend this. You could gate numerical information behind something like a good insight roll. This is fine, but even in this case you should lean on qualitative descriptions of how some character treats a player character. You can also keep the entire system completely to yourself, as a useful tool for the GM to structure descriptions and interactions. In this approach players do not get to actually know numerical values and you never have to reveal or justify movements in numerical values. This is probably your best bet. In this case the framework is still useful for figuring out how much the charisma of the character has helped the efforts of the player.

### Social Perception

"Social perception" is used here to refer to skills that allow you to roll to sense motives, detect deceit, and gain insight into another character's emotional state. It's important here to establish when *exactly* these skills are used and checks are made.

When a player asks a question that would fall under "social perception" about another character, they should first be given a superficial description of the character and their apparent emotional state. If the character in question seems to be at ease, the GM should just say so. This is true even if the character in question is only pretending to be at ease, but plans to attack or betray the player's character. It does not take a roll to be told that someone yelling and brandishing a knife is probably somewhat unhappy. The rules and skills for social perception are not meant to cover the superficial. These rules are for attempts to read another character. Social perception rolls are very similar to other character conflicts, they can be either a check or a contest.
v
### Social Checks

When the roll is a check, the DC will likely be a default DC of 6 + SOCIAL (and/or relevant skills). If you are trying to read a character who is is lying the DC will be set by their initial attempt to lie, which will have been a check + SOCIAL (and/or relevant skills) against your passive social perception. If they attempt to lie and fail this check, then whatever they said will be described as highly suspicious or likely a lie. If they succeed in their initial check, but you pass their DC when you attempt to read them, you will notice that something seems wrong, or suspicious, or you'll notice strange nervous habits.

Social perception rolls are almost always checks. If you are lying to someone, you perform a check. If they are trying to figure out if you are lying, they perform a check. If someone is trying to convince you of something and you think they might be lying, you perform a check. 

#### Social Check Resolution

In the case of a tie, resolution is the same as any other check. Defender wins. Otherwise there are four possible outcomes. 

***If you pass the check more than 3, Complete Success:***

You read the defender like an open book. You get a full answer to whatever question you were asking, or as full an answer as you could get from watching someone. They crumble at your gaze. Maybe they are so caught off guard that they fumble and make an embarrassing mistake, mentioning something they should not have.

***If you pass the check by 3 or less, Moderate Success:***

You get some insight into the question you were asking. If you are trying to see if someone is lying, you'll know that they're certainly not telling the whole truth, that they are actively misleading you. If you're trying to get insight into someone's emotional state, you get a good idea of how they are feeling. You might be able to tell that someone is distressed and trying to hide it. This is a pretty good read of someone, and they do not know that you know anything.

***If you fail the check by 3 or less, Moderate Failure:***

You have no answer to your question at all and the person you were attempting to read knows the vague shape of the question you asked or that you have a question. If you were trying to figure out if someone was lying about a specific claim they might know that you don't trust them or that you suspect them in some way. Otherwise, you might just be staring and it's weird.

***If you fail the check by more than 3, Catastrophic Failure:***

God have mercy on your soul. You completely give yourself away, your interests and your question are written all over your face. If you are trying to catch a lie, not only is it clear what exactly you think is being lied about, it's clear that you have *no* idea if the defender is lying. Maybe you scoffed at a specific claim, maybe you blurt out "But the stone of Macguffin!" at exactly the wrong time. Your face is very red.

### Contests

Contests are far rarer than checks. Social perception contests happen in contexts where it is understood that both parties are trying to advance their own interests and, if not outright lying, being very selective with the truth. Some examples of this would be a tense negotiation, an official dinner of ambassadors whose states are on the brink of war, a game of poker, spies meeting to trade secrets while not revealing their true intentions. In these cases checks would be happening simultaneously anyway, and the information that someone might doubt what you are saying or that they might not be telling the whole truth wouldn't be very meaningful.

Contest Resolution is just about the same as check resolution. The difference between the rolls of the two characters determines which character succeeds and which fails, and to what degree. This success and failure are captured by the same event. For example one character might give away information they shouldn't have, which captures both the success of one character and the failure of another.

Ties are just ties, a staredown, a tense silence. If your group prefers, ties can be resolved in the normal way for a contest: win goes to the higher modifier, if that's a tie, it's a tie in game, if that makes no sense, do it again.

## Odds and Ends

Some rules that did not fit nicely into a cohesive category.

### Stealth

Stealth is an AGI check (+STEALTH if you have it) against the defender’s passive perception. It’s a check against a passive score, and that is always 6 + SCORE.

### Grappling

Entering grappling takes (2n1), it's an attack + AGI To-Hit followed by a STR contest. If the part entering the grapple wins, both parties are \[grappling] but only the defender is \[vulnerable]. Defender can spend (2n1) to trigger another STR contest to try and break free. Defender can do nothing else.

#### Taking a Hostage

Same as above, but the attacker rolls one fewer die on the initial grapple check. They can attack the defender during the grapple provided they have a \[range: 0] weapon.

### Fall Damage

Fall damage is a d6 for every 6 spaces up to 25d6.

### Taking 10

You can take 10 minutes to work at something (that you can try repeatedly at where there is no cost for failure) to treat your check as a 10 + relevant modifiers.

## Encumbrance and Rations

Encumbrance is measured in encs. Encs are a combined measure of weight and unwieldiness. Most weapons are 1 enc. A \[heavy] weapon is 2 encs. A days worth of food and water is 1. 3 small items, like a book, a dagger, and some bandages together take 1 enc. Negligible items like quills and needles don't take up any encs, unless the DM determines you are carrying "way too many".  

Players must describe and account for how they are moving their things. They take "reasonable" penalties for impractical methods. If they tie a bunch of swords together and then hang that off of their neck, they will have a hard time stealthing. If they fall over while wearing the described necklace of dangerous wind chimes they're going to have a bad time.

### Storage Spaces, The "Personal" Space and Bags

"Storage space" is used to broadly refer to any place you can put things. Each storage space you have can be thought of as a source of a max encumbrance and a source of an \[encumbered] threshold. Most of the time you will have two storage spaces: 

- Your "personal" space, which includes anything you're carrying that isn't itself a storage space. Most often this would be your weapons and armor. 

- Your bag. This is most often some kind of backpack.

You have a personal \[encumbered] threshold. This is used for the weapons and armor you are carrying without a bag.
Your personal \[encumbered] threshold is 3 + STR. Your personal max encumbrance is 6 + STR encs.

The primary use of a bag is to give you more \[encumbered] thresholds and to change your maximum encumbrance.

Bags have varying \[encumbered] thresholds and max encumbrances. If a bag does not say it has an \[encumbrance] threshold, then it never makes you \[encumbered]. This is common for small bags that don't have a max encumbrance high enough to be able to encumber, or bags that are designed not to encumber.

Removing a bag is (2n1).

Searching a bag is (2n1).

### The \[encumbered] Threshold and Maximum Encumbrance

If you are past any encumbrance threshold in any storage space, you are \[encumbered], you have the \[encumbered] status.

The \[encumbered] status lowers your move speed by 1. Your Defense is lowered by 3. Additionally, take a -1 to all AGI checks.

If you aren't wearing heavy armor but you're carrying enough in your bag to pass the bag's encumbrance threshold, you are \[encumbered]. Less obviously, this also means that if you are past your personal encumbrance threshold (most likely from carrying weapons and wearing armor that are too heavy for you to move freely with) but you are not past your \[encumbered] threshold for your bag, you are still \[encumbered].  

In order to avoid passing an \[encumbered] threshold you likely want to spread the weight around multiple storage spaces, keeping under all of their \[encumbered] thresholds, or you might want to just put everything in a bag so that in a fight you can take it off quickly and not be \[encumbered].

You cannot carry more encs in total than your single highest max encumbrance score. This does not mean that having one storage space where you can carry 8 encs means that you must be able to carry 8 encs in every storage space, it just means that all together you can't carry more than 8 encs.

Unless otherwise specified, you can only use one bag at a time. If some mechanic allows you to use multiple bags, you cannot carry in total more than your highest max encumbrance from a single source, though you can move encs around to try to avoid the \[encumbered] status effect.

Your \[encumbered] threshold and your maximum encumbrance can be affected by status effects or skills, but most often they will be affected by the bag you are using.